name: Latest blog post workflow
on: 
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:  # Allows manual triggering
jobs: 
  update-readme-with-blog: 
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ✅ Grants write access to the repo
    steps: 
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with: 
          max_post_count: "4"
          feed_list: "https://medium.com/feed/@fernandoprashantha"
